{{- if .Values.basicAuth.enabled -}}


apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gotenberg.fullname" . }}
  labels:
    app: {{ template "gotenberg.name" . }}
    chart: {{ template "gotenberg.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  auth: {{ (printf "%s:%s"  .Values.basicAuth.username .Values.basicAuth.passwordMD5) | b64enc | quote }}
{{- end }}

