apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "matomo.fullname" . }}
  labels:
{{ include "matomo.labels" . | indent 4 }}
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;


    events {
        worker_connections  1024;
    }


    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        include /etc/nginx/conf.d/matomo.conf;
    }

  matomo.conf: |
    upstream php-handler {
        server localhost:9000;
    }

    server {
        listen 80 default_server;
        root {{ .Values.persistence.path }};
        index index.php index.html;

        location / {
            try_files $uri $uri/ =404;
        }

        location ~ \.php$ {
            fastcgi_pass php-handler;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }

        location = /health-check {
            access_log off;
            default_type application/json;
            return 200 '{"status": "ok"}';
        }
    }

  www.conf: |
    [www]
    user = www-data
    group = www-data

    listen = 127.0.0.1:9000

    pm = dynamic
    pm.max_children = 5
    pm.start_servers = 2
    pm.min_spare_servers = 1
    pm.max_spare_servers = 3
    pm.status_path = /status
