{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "matomo.serviceAccountName" . }}
  labels:
{{ include "matomo.labels" . | indent 4 }}
{{- end -}}
