replicaCount: 1
env:
  open:
    THUMBOR_NUM_PROCESSES: "1"
    CORS_ALLOW_ORIGIN: "*"
    AUTO_WEBP: "True"
    RESULT_STORAGE: "thumbor.result_storages.no_storage"
    RESULT_STORAGE_STORES_UNSAFE: "True"
    STORAGE: "thumbor.storages.file_storage"
    HEALTHCHECK_ROUTE: "/healthcheck"
    THUMBOR_PORT: "80"
    MAX_AGE: "3600"
    MAX_AGE_TEMP_IMAGE: "300"
    RESULT_STORAGE_EXPIRATION_SECONDS: "31536000"
    ALLOW_UNSAFE_URL: "True"
    LOG_LEVEL: "error"

auth:
  enabled: true
  username: "thumbor" # Username
  password: "$1$nwVVjM_Y$VeLOyr0CIIMXQajJL2pXT1" # Password generated via htpasswd (password)
  # existingSecret: specify the name of a existing secret

# Some Configs should be set via config-file and not as environment variable
conf:
  allowedSources: "'http://domain_or_wildcard', 'comma_seperated'"

ingress:
  hosts:
    - "thumbor.domain"
  # Use this if you are using Traefik as your ingress-router
  # path: "/scale"
  # Use this if you are using nginx as your ingress-router
  path: "/scale(/|$)(.*)"
  annotations:
    # rules to strip the /scale path
    # Use this if you are using Traefik as your ingress-router
    # traefik.frontend.rule.type: PathPrefixStrip # Use this if you are using Traefik as your ingress-router
    # Use this if you are using nginx as your ingress-router
    nginx.ingress.kubernetes.io/rewrite-target: /$2

image:
  repository: registry.hub.docker.com/minimalcompact/thumbor
  tag: 6.7.5
  pullPolicy: IfNotPresent

service:
  name: thumbor
  type: ClusterIP

persistence:
  enabled: false
  storageClass: generic
  accessMode: ReadWriteOnce
  size: 8Gi

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 1
    memory: 512Mi
