replicaCount: 1
env:
  open:
    LOG_LEVEL: "error"
    THUMBOR_PORT: "80"

# Some Configs should be set via config-file and not as environment variable
conf:
  allowedSources: "'http://domain_or_wildcard', 'comma_seperated'"
  respectOrientation: "False"
  resultStorage: "'thumbor.result_storages.file_storage'"
  allowUnsafeUrl: "True"
  resultStorageExpirationSeconds: "86400"
  maxAge: "259200"
  maxAgeTempImage: "60"
  storageExpirationSeconds: "86400"

ingress:
  hosts:
    - "thumbor.domain"
  # Use this if you are using Traefik as your ingress-router
  # path: "/scale"
  # Use this if you are using nginx as your ingress-router
  path: "/scale(/|$)(.*)"
  annotations:
    # rules to strip the /scale path
    # Use this if you are using Traefik as your ingress-router
    # traefik.frontend.rule.type: PathPrefixStrip # Use this if you are using Traefik as your ingress-router
    # Use this if you are using nginx as your ingress-router
    nginx.ingress.kubernetes.io/rewrite-target: /$2

image:
  repository: registry.hub.docker.com/minimalcompact/thumbor
  tag: 6.7.5
  pullPolicy: IfNotPresent

service:
  name: thumbor
  type: ClusterIP

persistence:
  enabled: false
  storageClass: generic
  accessMode: ReadWriteOnce
  size: 8Gi

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 1
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
