apiVersion: v1
kind: Secret
metadata:
  name: secrets
  labels:
    app: "{{ template "offen.name" . }}"
    chart: "{{ template "offen.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}  
type: Opaque
data:
  {{- range $key, $val := .Values.env.secret }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end}}


--- 

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "offen.fullname" . }}-database
  labels:
    app: "{{ template "offen.name" . }}"
    chart: "{{ template "offen.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}  
type: Opaque
data:
  {{- if index .Values "mariadb-galera" "enabled" }}
  {{- $mysqlServiceName := printf "%s-mariadb-galera.%s.svc.cluster.local" (include "offen.fullname" . ) .Values.config.namespace }}
  OFFEN_DATABASE_CONNECTIONSTRING: {{ printf "mysql://%s:%s@%s:3306/%s?serverVersion=mariadb-10.4.13" (index .Values "mariadb-galera" "db" "user") (index .Values "mariadb-galera" "db" "password") $mysqlServiceName (index .Values "mariadb-galera" "db" "name") | b64enc }}
  {{ else if index .Values "mariadb-galera" "remote"}}
  {{- $mysqlServiceName := printf "%s" (index .Values "mariadb-galera" "remote") }}
  OFFEN_DATABASE_CONNECTIONSTRING: {{ printf "mysql://%s:%s@%s:3306/%s?serverVersion=mariadb-10.4.13" (index .Values "mariadb-galera" "db" "user") (index .Values "mariadb-galera" "db" "password") $mysqlServiceName (index .Values "mariadb-galera" "db" "name") | b64enc }}
  {{ else }}
  OFFEN_DATABASE_CONNECTIONSTRING: {{ "/var/opt/offen/offen.db" | b64enc }}
  {{ end }}


