apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "matomo.fullname" . }}
  labels:
{{ include "matomo.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "matomo.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "matomo.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "matomo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: fastcgi
              containerPort: 9000
              protocol: TCP
          volumeMounts:
            - name: {{ include "matomo.fullname" . }}
              mountPath: /usr/local/etc/php-fpm.d/www.conf
              subPath: www.conf
            - name: matomo-volume
              mountPath: {{ .Values.persistence.path }}
              subPath: html
          livenessProbe:
            tcpSocket:
              port: fastcgi
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: fastcgi
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: {{ .Chart.Name }}-nginx
          securityContext:
            {{- toYaml .Values.nginx.securityContext | nindent 12 }}
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: {{ include "matomo.fullname" . }}
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: {{ include "matomo.fullname" . }}
              mountPath: /etc/nginx/conf.d/matomo.conf
              subPath: matomo.conf
            - name: matomo-volume
              mountPath: {{ .Values.persistence.path }}
              subPath: html
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
      volumes:
        - name: matomo-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}
        - name: {{ include "matomo.fullname" . }}
          configMap:
            name: {{ include "matomo.fullname" . }}
            items:
              - key: nginx.conf
                path: nginx.conf
                mode: 292
              - key: matomo.conf
                path: matomo.conf
                mode: 292
              - key: www.conf
                path: www.conf
                mode: 292
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
