{{- if .Values.verticalAutoscaling.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "gotenberg.fullname" . }}
  labels:
    {{ include "gotenberg.labels" . | nindent 4 }}
    app: {{ template "gotenberg.name" . }}
    chart: {{ template "gotenberg.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "gotenberg.fullname" . }}
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
      - containerName: {{ .Chart.Name }}
        minAllowed:
            cpu: {{ .Values.verticalAutoscaling.minAllowed }}
{{- end }}
