apiVersion: v1
kind: Service
metadata:
  name: {{ template "statping.fullname" . }}
  labels:
    app: {{ template "statping.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: {{ .Values.service.name }}
  selector:
    app: {{ template "statping.name" . }}
    release: {{ .Release.Name }}