apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "thumbor.fullname" . }}-config
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "thumbor.name" . }}
data:
  thumbor.conf: |
    ALLOWED_SOURCES =  [{{ .Values.conf.allowedSources }}]
    FILE_STORAGE_ROOT_PATH = '/data/storage/source'
    DETECTORS = [{{ .Values.conf.detectors }}]
    FACE_DETECTOR_CASCADE_FILE = 'haarcascade_frontalface_alt.xml'
    GLASSES_DETECTOR_CASCADE_FILE = 'haarcascade_eye_tree_eyeglasses.xml'
    PROFILE_DETECTOR_CASCADE_FILE = 'haarcascade_profileface.xml'
    RESULT_STORAGE_FILE_STORAGE_ROOT_PATH = '/data/storage/result'
