{{- $fullName := include "thumbor.fullname" . -}}
{{- $servicePath := .Values.ingress.path -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  {{- if or (.Values.ingress.annotations) (.Values.auth.enabled) }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: {{ template "thumbor.name" . }}-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - Thumbor'
{{- end }}
  labels:
    app: {{ template "thumbor.name" . }}
    chart: {{ template "thumbor.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .labels }}
{{ toYaml .labels | indent 4 }}
{{- end }}
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: {{ $servicePath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: 80
  {{- end }}
