{{- if .Values.auth.enabled -}}
{{- if not .Values.auth.existingSecret -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "thumbor.fullname" . }}-auth
  labels:
    chart: {{ template "thumbor.name" . }}
    app: {{ template "thumbor.name" . }}
    chart: {{ template "thumbor.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}   
type: Opaque
data:
  auth: {{ print .Values.auth.username ":" .Values.auth.password | b64enc }}
{{ end }}
{{ end }}