apiVersion: v1
kind: Service
metadata:
  name: {{ template "thumbor.fullname" . }}
  labels:
    app: {{ template "thumbor.name" . }}
    chart: {{ template "thumbor.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: {{ .Values.service.name }}
  selector:
    app: {{ template "thumbor.name" . }}
    release: {{ .Release.Name }}