name: Lint and Test Charts

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: 
      - master
      - develop

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.4.0

      - uses: actions/setup-python@v5.1.1
        with:
          python-version: 3.12.4

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

  install-chart:
    name: install-chart
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s:
          - v1.30
          - v1.29
          - v1.28
          - v1.27
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.10.0
      - uses: actions/setup-python@v5.1.1
        with:
          python-version: 3.12.4
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1    
      - name: Create kind ${{ matrix.k8s }} cluster
        uses: helm/kind-action@v1.10.0
        with:
          node_image: kindest/node:${{ matrix.k8s }}
      - name: Run chart-testing (install) ${{ matrix.k8s }}
        run: ct install --all
